export default {
	PROD_URL: 'https://casquads.com/',
	LICENSES: [
		'ukraine',
		'curacao',
		'UKGC',
		'alderney',
		'belgium',
		'gibraltar',
		'denmark',
		'canavec',
		'costa_rica',
		'malta',
		'isle_of_man'
	],
	PAYMENTS: [
		'visa',
		'qiwi',
		'mastercard',
		'webMoney',
		'maestro',
		'yandex',
		'bitcoin',
		'pm',
		'ethereum',
		'pay',
		'privat',
		'mono',
		'kuna',
		'global_money',
		'binance',
		'binance_pay',
		'tether_trc',
		'tether_erc',
		'adv_cash',
		'google_pay'
	],
	TYPE_CONTENT: ['default', 'warning', 'attention'],
	VENDOR_LICENSES: [
		'ukraine',
		'curacao',
		'UKGC',
		'alderney',
		'belgium',
		'gibraltar',
		'denmark',
		'canavec',
		'costa_rica',
		'malta',
		'isle_of_man'
	],
	GEO: ['WORLD', 'GB', 'BD', 'AU', 'GR', 'IN', 'ID', 'CA', 'NL', 'DE', 'ZA', 'PH', 'SE'],
	AUTHOR_ROLES: ['Editor-in-Chief', 'Editor Writer']
}
