export default {
	PROD_URL: 'https://casquad.com/',
	LICENSES: [
		'ukraine',
		'curacao',
		'UKGC',
		'alderney',
		'belgium',
		'gibraltar',
		'denmark',
		'canavec',
		'costa_rica',
		'malta',
		'isle_of_man'
	],
	PAYMENTS: [
		'visa',
		'qiwi',
		'mastercard',
		'webMoney',
		'maestro',
		'yandex',
		'bitcoin',
		'pm',
		'ethereum',
		'pay',
		'privat',
		'mono',
		'kuna',
		'global_money',
		'binance',
		'binance_pay',
		'tether_trc',
		'tether_erc',
		'adv_cash',
		'google_pay'
	],
	TYPE_CONTENT: ['default', 'warning', 'attention'],
	VENDOR_LICENSES: [
		'ukraine',
		'curacao',
		'UKGC',
		'alderney',
		'belgium',
		'gibraltar',
		'denmark',
		'canavec',
		'costa_rica',
		'malta',
		'isle_of_man'
	],
	GEO: ['WORLD', 'GB', 'BD', 'AU', 'GR', 'IN', 'ID', 'CA', 'NL', 'DE', 'ZA', 'PH', 'SE'],
	AUTHOR_ROLES: ['Editor-in-Chief', 'Editor Writer'],
	LABELS: ['popular', 'new', 'trusted', 'best'],
	BLOG_TEMPLATE_COMPONENTS: {
		breadcrumbs: 1,
		banner: 2,
		nav_menu: 3,
		content_1: 4,
		top_casinos: 5,
		content_2: 6,
		games: 7,
		content_4: 8,
		content_5: 9,
		content_6: 10,
		content_7: 11,
		content_8: 12,
		pros_cons: 13,
		content_9: 14,
		content_10: 15,
		author_summary: 16,
		reviews: 17
	},
	SLOT_TEMPLATE_COMPONENTS: {
		breadcrumbs: 1,
		top_card: 2,
		nav_menu: 3,
		top_casinos: 4,
		video: 5,
		characters: 6,
		details: 7,
		rtp: 8,
		symbols: 9,
		screenshots: 10,
		content: 11,
		mobile_version: 12,
		pros_cons: 13,
		bonuses: 14,
		games: 15,
		faq: 16,
		reviews: 17,
		author_summary: 18
	},
	FUNNEL_TEMPLATE_COMPONENTS: {
		breadcrumbs: 1,
		banner: 2,
		nav_menu: 3,
		content_1: 4,
		top_casinos: 5,
		content_2: 6,
		games: 7,
		content_4: 8,
		video: 9,
		content_5: 10,
		content_6: 11,
		content_7: 12,
		content_8: 13,
		pros_cons: 14,
		content_9: 15,
		content_10: 16,
		faq: 17,
		reviews: 18,
		author_summary: 19
	}
}
